<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SAI-PC" ignored="0" name="RetryMultipleFailedTestcases" tests="9" failures="2" timestamp="20 Nov 2018 14:02:26 GMT" time="0.283" errors="0">
  <testcase name="test1" time="0.016" classname="mytests.MyTest">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.011" classname="mytests.MyTest">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.005" classname="mytests.MyTest">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.007" classname="mytests.MyTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at mytests.MyTest.test1(MyTest.java:12)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.002" classname="mytests.MyTest">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.013" classname="mytests.MyTest">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.006" classname="mytests.MyTest">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.001" classname="mytests.MyTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at mytests.MyTest.test2(MyTest.java:18)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.003" classname="mytests.MyTest"/>
</testsuite> <!-- RetryMultipleFailedTestcases -->
